color0 #151313
color1 #ffb4ab
color2 #e1bebe
color3 #d5c2c2
color4 #d5c5a7
color5 #e1bebe
color6 #d5c2c2
color7 #e8e1e0
color8 #9c8d8d
color9 #ffb4ab
color10 #e1bebe
color11 #d5c2c2
color12 #d5c5a7
color13 #e1bebe
color14 #d5c2c2
color15 #e8e1e0

cursor                #e8e1e0
cursor_text_color     #151313
background            #151313
foreground            #e8e1e0
selection_foreground  #d3c3c2
selection_background  #4f4444
active_border_color   #e1bebe
inactive_border_color #4f4444
url_color             #e1bebe

active_tab_foreground   #412b2b
active_tab_background   #e1bebe
inactive_tab_foreground #d3c3c2
inactive_tab_background #4f4444
cursor_trail_color      #d3c3c2
