color0 #131314
color1 #ffb4ab
color2 #b6cacf
color3 #c1c8ca
color4 #cdc2d6
color5 #b6cacf
color6 #c1c8ca
color7 #e4e2e2
color8 #8c9293
color9 #ffb4ab
color10 #b6cacf
color11 #c1c8ca
color12 #cdc2d6
color13 #b6cacf
color14 #c1c8ca
color15 #e4e2e2

cursor                #e4e2e2
cursor_text_color     #131314
background            #131314
foreground            #e4e2e2
selection_foreground  #c2c7c9
selection_background  #424849
active_border_color   #b6cacf
inactive_border_color #424849
url_color             #b6cacf

active_tab_foreground   #213337
active_tab_background   #b6cacf
inactive_tab_foreground #c2c7c9
inactive_tab_background #424849
cursor_trail_color      #c2c7c9
