color0 #1d0f12
color1 #ffb4ab
color2 #ffb2bf
color3 #ffb2bf
color4 #ffb692
color5 #ffb2bf
color6 #ffb2bf
color7 #f8dcdf
color8 #a9898d
color9 #ffb4ab
color10 #ffb2bf
color11 #ffb2bf
color12 #ffb692
color13 #ffb2bf
color14 #ffb2bf
color15 #f8dcdf

cursor                #f8dcdf
cursor_text_color     #1d0f12
background            #1d0f12
foreground            #f8dcdf
selection_foreground  #e2bec2
selection_background  #5a4044
active_border_color   #ffb2bf
inactive_border_color #5a4044
url_color             #ffb2bf

active_tab_foreground   #660027
active_tab_background   #ffb2bf
inactive_tab_foreground #e2bec2
inactive_tab_background #5a4044
cursor_trail_color      #e2bec2
